# Palworld Dedicated Server
# Uses thijsvanloef/palworld-server-docker image
# Documentation: https://github.com/thijsvanloef/palworld-server-docker

services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: palworld
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    environment:
      PUID: "1000"
      PGID: "1000"
      PORT: "8211"
      PLAYERS: "16"
      SERVER_PASSWORD: ""  # Leave empty for no password
      MULTITHREADING: "true"
      COMMUNITY: "false"
      SERVER_NAME: "Palworld Server"
      SERVER_DESCRIPTION: "A Palworld Dedicated Server managed by GSM"
      ADMIN_PASSWORD: "changeme"  # CHANGE THIS - used for RCON
      UPDATE_ON_BOOT: "true"
      # Auto restart on crash
      AUTO_RESTART_ENABLED: "true"
      AUTO_RESTART_WARN_MINUTES: "5"
    volumes:
      - /var/opt/container-volumes/palworld:/palworld
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
